version: "3.9"
services:
  db :
    image: postgres:14.5
    volumes:
      - data:/varlib/postgresql/data
    env_file:
      - ./.env

    networks:
      - women
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn djPR.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/djPR
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - women
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#      - db
#    networks:
#      - engineer-network

networks:
  women:
    driver: bridge
volumes:
  data:
